# Generated by Django 4.1.3 on 2022-11-16 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Inventoy", new_name="Inventory",),
    ]
